// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: guardian.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuardianAI_PredictDomain_FullMethodName = "/guardian.GuardianAI/PredictDomain"
)

// GuardianAIClient is the client API for GuardianAI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuardianAIClient interface {
	PredictDomain(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*PredictionResponse, error)
}

type guardianAIClient struct {
	cc grpc.ClientConnInterface
}

func NewGuardianAIClient(cc grpc.ClientConnInterface) GuardianAIClient {
	return &guardianAIClient{cc}
}

func (c *guardianAIClient) PredictDomain(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*PredictionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictionResponse)
	err := c.cc.Invoke(ctx, GuardianAI_PredictDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuardianAIServer is the server API for GuardianAI service.
// All implementations must embed UnimplementedGuardianAIServer
// for forward compatibility.
type GuardianAIServer interface {
	PredictDomain(context.Context, *DomainRequest) (*PredictionResponse, error)
	mustEmbedUnimplementedGuardianAIServer()
}

// UnimplementedGuardianAIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuardianAIServer struct{}

func (UnimplementedGuardianAIServer) PredictDomain(context.Context, *DomainRequest) (*PredictionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PredictDomain not implemented")
}
func (UnimplementedGuardianAIServer) mustEmbedUnimplementedGuardianAIServer() {}
func (UnimplementedGuardianAIServer) testEmbeddedByValue()                    {}

// UnsafeGuardianAIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuardianAIServer will
// result in compilation errors.
type UnsafeGuardianAIServer interface {
	mustEmbedUnimplementedGuardianAIServer()
}

func RegisterGuardianAIServer(s grpc.ServiceRegistrar, srv GuardianAIServer) {
	// If the following call panics, it indicates UnimplementedGuardianAIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuardianAI_ServiceDesc, srv)
}

func _GuardianAI_PredictDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardianAIServer).PredictDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardianAI_PredictDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardianAIServer).PredictDomain(ctx, req.(*DomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuardianAI_ServiceDesc is the grpc.ServiceDesc for GuardianAI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuardianAI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guardian.GuardianAI",
	HandlerType: (*GuardianAIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PredictDomain",
			Handler:    _GuardianAI_PredictDomain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guardian.proto",
}
