// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: guardian.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainRequest) Reset() {
	*x = DomainRequest{}
	mi := &file_guardian_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainRequest) ProtoMessage() {}

func (x *DomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guardian_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainRequest.ProtoReflect.Descriptor instead.
func (*DomainRequest) Descriptor() ([]byte, []int) {
	return file_guardian_proto_rawDescGZIP(), []int{0}
}

func (x *DomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type PredictionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsMalicious     bool                   `protobuf:"varint,1,opt,name=is_malicious,json=isMalicious,proto3" json:"is_malicious,omitempty"`
	ConfidenceScore float32                `protobuf:"fixed32,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Category        string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PredictionResponse) Reset() {
	*x = PredictionResponse{}
	mi := &file_guardian_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionResponse) ProtoMessage() {}

func (x *PredictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guardian_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionResponse.ProtoReflect.Descriptor instead.
func (*PredictionResponse) Descriptor() ([]byte, []int) {
	return file_guardian_proto_rawDescGZIP(), []int{1}
}

func (x *PredictionResponse) GetIsMalicious() bool {
	if x != nil {
		return x.IsMalicious
	}
	return false
}

func (x *PredictionResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *PredictionResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_guardian_proto protoreflect.FileDescriptor

const file_guardian_proto_rawDesc = "" +
	"\n" +
	"\x0eguardian.proto\x12\bguardian\"'\n" +
	"\rDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"~\n" +
	"\x12PredictionResponse\x12!\n" +
	"\fis_malicious\x18\x01 \x01(\bR\visMalicious\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x02R\x0fconfidenceScore\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory2V\n" +
	"\n" +
	"GuardianAI\x12H\n" +
	"\rPredictDomain\x12\x17.guardian.DomainRequest\x1a\x1c.guardian.PredictionResponse\"\x00B#Z!github.com/1OSA/guardian-ai/protob\x06proto3"

var (
	file_guardian_proto_rawDescOnce sync.Once
	file_guardian_proto_rawDescData []byte
)

func file_guardian_proto_rawDescGZIP() []byte {
	file_guardian_proto_rawDescOnce.Do(func() {
		file_guardian_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guardian_proto_rawDesc), len(file_guardian_proto_rawDesc)))
	})
	return file_guardian_proto_rawDescData
}

var file_guardian_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_guardian_proto_goTypes = []any{
	(*DomainRequest)(nil),      // 0: guardian.DomainRequest
	(*PredictionResponse)(nil), // 1: guardian.PredictionResponse
}
var file_guardian_proto_depIdxs = []int32{
	0, // 0: guardian.GuardianAI.PredictDomain:input_type -> guardian.DomainRequest
	1, // 1: guardian.GuardianAI.PredictDomain:output_type -> guardian.PredictionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_guardian_proto_init() }
func file_guardian_proto_init() {
	if File_guardian_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guardian_proto_rawDesc), len(file_guardian_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guardian_proto_goTypes,
		DependencyIndexes: file_guardian_proto_depIdxs,
		MessageInfos:      file_guardian_proto_msgTypes,
	}.Build()
	File_guardian_proto = out.File
	file_guardian_proto_goTypes = nil
	file_guardian_proto_depIdxs = nil
}
